name: Build and Publish to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  build-pack-publish:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET 8 SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: CalculatorApp

    - name: Build in Release mode
      run: dotnet build -c Release --no-restore
      working-directory: CalculatorApp

    - name: Pack NuGet package
      run: |
        VERSION="1.0.${{ github.run_number }}"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        dotnet pack -c Release -p:PackageVersion=$VERSION --no-build -o ./nupkg
      working-directory: CalculatorApp

    - name: Publish package to GitHub Packages
      run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --skip-duplicate
      working-directory: CalculatorApp