name: Build and Publish to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  build-pack-publish:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: CalculatorApp

    - name: Build in Release mode
      run: dotnet build -c Release --no-restore
      working-directory: CalculatorApp

    - name: Pack NuGet package (static version from .csproj)
      run: dotnet pack -c Release --no-build -o ./nupkg
      working-directory: CalculatorApp

    - name: Publish package to GitHub Packages
      run: dotnet nuget push ./nupkg/*.nupkg \ --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --skip-duplicate
      working-directory: CalculatorApp