name: Build and Publish CalculatorApp with MathNet

on:
  push:
    branches: [ features/yml_test ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    env:
      PACKAGE_VERSION: 1.0.${{ github.run_number }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Add GitHub Packages Source
        run: dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --name github --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text

      - name: Restore Dependencies
        run: dotnet restore CalculatorApp/CalculatorApp.csproj

      - name: Build Project
        run: dotnet build CalculatorApp/CalculatorApp.csproj --configuration Release

      - name: Inject Version Number
        run: |
          sed -i "s|<VersionPrefix>.*</VersionPrefix>|<VersionPrefix>${{ env.PACKAGE_VERSION }}</VersionPrefix>|" CalculatorApp/CalculatorApp.csproj

      - name: Pack Project
        run: dotnet pack CalculatorApp/CalculatorApp.csproj --configuration Release --output ./nupkg

      - name: Push to GitHub Packages
        run: dotnet nuget push ./nupkg/*.nupkg --source github --api-key ${{ secrets.GITHUB_TOKEN }}